//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonRehber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisanlar
    {
        public int calisanId { get; set; }
        public string calisanAd { get; set; }
        public string calisanSoyad { get; set; }
        public string telefon { get; set; }
        public Nullable<int> departman { get; set; }
        public string yöneticiBilgiler { get; set; }
        public Nullable<bool> yöneticiMi { get; set; }
    
        public virtual Departmanlar Departmanlar { get; set; }
    }
}
